import { VideoContent, Category, CapsuleVideo, ArticleContent, Game, Room, Formation, JobOffer } from '../types';

// Mock Categories
export const MOCK_CATEGORIES: Category[] = [
  {
    id: '1',
    name: 'Témoignage',
    icon: 'person',
    color: 'black',
  },
  {
    id: '2',
    name: 'Carrière',
    icon: 'briefcase',
    color: 'black',
  },
  {
    id: '3',
    name: 'Tech',
    icon: 'hardware-chip',
    color: 'black',
  },
  {
    id: '4',
    name: 'Leadership',
    icon: 'star',
    color: 'black',
  },
  {
    id: '5',
    name: 'Marketing',
    icon: 'megaphone',
    color: 'black',
  },
  {
    id: '6',
    name: 'Design',
    icon: 'color-palette',
    color: 'black',
  },
  {
    id: '7',
    name: 'Business',
    icon: 'trending-up',
    color: 'black',
  },
];

// Mock Video Content
export const MOCK_VIDEOS: VideoContent[] = [
  {
    id: '1',
    title: "Comment j'ai développé ma carrière en tech en 6 mois",
    description:
      'Julie partage son parcours et ses conseils pour une reconversion réussie',
    thumbnail: 'https://picsum.photos/400/700?random=1',
    creator: {
      id: 'c1',
      name: 'Julie Chen',
      avatar: 'https://i.pravatar.cc/150?img=5',
      verified: true,
    },
    category: MOCK_CATEGORIES[0],
    duration: '4:30',
    matchPercentage: 98,
    engagement: {
      likes: 342,
      comments: 30,
      shares: 15,
      bookmarks: 45,
    },
    tags: ['reconversion', 'tech', 'carrière'],
    createdAt: '2024-11-01T10:00:00Z',
  },
  {
    id: '2',
    title: '5 erreurs à éviter lors de votre première startup',
    description:
      "Marc, entrepreneur serial, révèle les pièges communs et comment les éviter",
    thumbnail: 'https://picsum.photos/400/700?random=2',
    creator: {
      id: 'c2',
      name: 'Marc Dubois',
      avatar: 'https://i.pravatar.cc/150?img=12',
      verified: true,
    },
    category: MOCK_CATEGORIES[6],
    duration: '6:15',
    matchPercentage: 92,
    engagement: {
      likes: 521,
      comments: 67,
      shares: 28,
      bookmarks: 89,
    },
    tags: ['startup', 'entrepreneuriat', 'business'],
    createdAt: '2024-11-02T14:30:00Z',
  },
  {
    id: '3',
    title: 'Les secrets du design thinking en 2024',
    description:
      "Sarah explique comment le design thinking transforme les organisations",
    thumbnail: 'https://picsum.photos/400/700?random=3',
    creator: {
      id: 'c3',
      name: 'Sarah Martin',
      avatar: 'https://i.pravatar.cc/150?img=9',
      verified: false,
    },
    category: MOCK_CATEGORIES[5],
    duration: '5:45',
    matchPercentage: 87,
    engagement: {
      likes: 289,
      comments: 42,
      shares: 19,
      bookmarks: 56,
    },
    tags: ['design', 'innovation', 'méthode'],
    createdAt: '2024-11-03T09:15:00Z',
  },
  {
    id: '4',
    title: "De développeur junior à lead en 2 ans : mon parcours",
    description:
      'Ahmed partage les compétences techniques et soft skills qui ont fait la différence',
    thumbnail: 'https://picsum.photos/400/700?random=4',
    creator: {
      id: 'c4',
      name: 'Ahmed Benali',
      avatar: 'https://i.pravatar.cc/150?img=15',
      verified: true,
    },
    category: MOCK_CATEGORIES[2],
    duration: '7:20',
    matchPercentage: 95,
    engagement: {
      likes: 678,
      comments: 94,
      shares: 45,
      bookmarks: 112,
    },
    tags: ['développement', 'carrière', 'leadership'],
    createdAt: '2024-11-04T11:00:00Z',
  },
  {
    id: '5',
    title: 'Marketing digital : les tendances 2024 à ne pas manquer',
    description:
      'Sophie décrypte les nouvelles stratégies qui fonctionnent vraiment',
    thumbnail: 'https://picsum.photos/400/700?random=5',
    creator: {
      id: 'c5',
      name: 'Sophie Laurent',
      avatar: 'https://i.pravatar.cc/150?img=20',
      verified: true,
    },
    category: MOCK_CATEGORIES[4],
    duration: '8:10',
    matchPercentage: 89,
    engagement: {
      likes: 445,
      comments: 58,
      shares: 32,
      bookmarks: 73,
    },
    tags: ['marketing', 'digital', 'stratégie'],
    createdAt: '2024-11-05T15:45:00Z',
  },
  {
    id: '6',
    title: 'Comment négocier son salaire : guide complet',
    description:
      'Emma, coach carrière, partage ses techniques éprouvées',
    thumbnail: 'https://picsum.photos/400/700?random=6',
    creator: {
      id: 'c6',
      name: 'Emma Rousseau',
      avatar: 'https://i.pravatar.cc/150?img=24',
      verified: false,
    },
    category: MOCK_CATEGORIES[1],
    duration: '6:50',
    matchPercentage: 93,
    engagement: {
      likes: 789,
      comments: 103,
      shares: 67,
      bookmarks: 145,
    },
    tags: ['carrière', 'négociation', 'salaire'],
    createdAt: '2024-11-06T08:30:00Z',
  },
  {
    id: '7',
    title: "L'intelligence artificielle va-t-elle remplacer votre job ?",
    description:
      'Thomas analyse l\'impact de l\'IA sur le marché du travail',
    thumbnail: 'https://picsum.photos/400/700?random=7',
    creator: {
      id: 'c7',
      name: 'Thomas Petit',
      avatar: 'https://i.pravatar.cc/150?img=33',
      verified: true,
    },
    category: MOCK_CATEGORIES[2],
    duration: '9:05',
    matchPercentage: 85,
    engagement: {
      likes: 567,
      comments: 156,
      shares: 89,
      bookmarks: 98,
    },
    tags: ['IA', 'futur', 'emploi'],
    createdAt: '2024-11-07T13:20:00Z',
  },
  {
    id: '8',
    title: 'Créer un side project rentable en 90 jours',
    description:
      'Lucas raconte comment il a lancé son SaaS en parallèle de son job',
    thumbnail: 'https://picsum.photos/400/700?random=8',
    creator: {
      id: 'c8',
      name: 'Lucas Bernard',
      avatar: 'https://i.pravatar.cc/150?img=41',
      verified: false,
    },
    category: MOCK_CATEGORIES[6],
    duration: '10:30',
    matchPercentage: 91,
    engagement: {
      likes: 892,
      comments: 127,
      shares: 78,
      bookmarks: 167,
    },
    tags: ['side-project', 'entrepreneuriat', 'SaaS'],
    createdAt: '2024-11-08T16:00:00Z',
  },
  {
    id: '9',
    title: 'Manager une équipe remote : les clés du succès',
    description:
      'Marie partage ses meilleures pratiques de management à distance',
    thumbnail: 'https://picsum.photos/400/700?random=9',
    creator: {
      id: 'c9',
      name: 'Marie Durand',
      avatar: 'https://i.pravatar.cc/150?img=47',
      verified: true,
    },
    category: MOCK_CATEGORIES[3],
    duration: '7:40',
    matchPercentage: 88,
    engagement: {
      likes: 412,
      comments: 71,
      shares: 44,
      bookmarks: 82,
    },
    tags: ['management', 'remote', 'leadership'],
    createdAt: '2024-11-09T10:45:00Z',
  },
  {
    id: '10',
    title: 'De 0 à 100k abonnés sur LinkedIn : ma stratégie',
    description:
      'Paul révèle sa méthode pour créer du contenu qui performe',
    thumbnail: 'https://picsum.photos/400/700?random=10',
    creator: {
      id: 'c10',
      name: 'Paul Moreau',
      avatar: 'https://i.pravatar.cc/150?img=52',
      verified: true,
    },
    category: MOCK_CATEGORIES[4],
    duration: '8:55',
    matchPercentage: 90,
    engagement: {
      likes: 723,
      comments: 98,
      shares: 134,
      bookmarks: 201,
    },
    tags: ['LinkedIn', 'personal-branding', 'content'],
    createdAt: '2024-11-10T12:15:00Z',
  },
];

// Mock User
export const MOCK_USER = {
  id: 'user1',
  name: 'Hajar Fahmani',
  email: 'Hajar@neoori.com',
  avatar: 'https://i.pravatar.cc/150?img=1',
  bio: 'Passionate about learning and professional development',
};

// Mock Capsule Videos
export const MOCK_CAPSULE_VIDEOS: CapsuleVideo[] = [
  {
    id: 'cap1',
    title: 'Comment développer sa confiance en soi en...',
    description: 'Techniques et conseils pratiques pour briller lors de tes entretiens',
    thumbnail: 'https://picsum.photos/400/600?random=11',
    author: {
      id: 'a1',
      name: 'Sophie Martin',
      avatar: 'https://i.pravatar.cc/150?img=10',
      verified: true,
    },
    duration: '4:30',
    category: 'Carrière',
    engagement: {
      likes: 234,
      bookmarks: 67,
    },
  },
  {
    id: 'cap2',
    title: 'Les bases du networking professionnel expliquées...',
    description: 'Comment créer et entretenir un réseau professionnel efficace',
    thumbnail: 'https://picsum.photos/400/600?random=12',
    author: {
      id: 'a2',
      name: 'Thomas Dubois',
      avatar: 'https://i.pravatar.cc/150?img=11',
      verified: false,
    },
    duration: '6:15',
    category: 'Leadership',
    engagement: {
      likes: 456,
      bookmarks: 123,
    },
  },
  {
    id: 'cap3',
    title: "Comment l'IA transforme les métiers du marketing",
    description: 'Un aperçu des nouvelles compétences à développer pour...',
    thumbnail: 'https://picsum.photos/400/600?random=13',
    author: {
      id: 'a3',
      name: 'Julie Chen',
      avatar: 'https://i.pravatar.cc/150?img=12',
      verified: true,
    },
    duration: '5:45',
    category: 'Tech',
    engagement: {
      likes: 789,
      bookmarks: 234,
    },
  },
  {
    id: 'cap4',
    title: '3 exercices pour améliorer ton leadership au quotidien',
    description: 'Des pratiques simples pour développer tes compétences de...',
    thumbnail: 'https://picsum.photos/400/600?random=14',
    author: {
      id: 'a4',
      name: 'Marc Leroy',
      avatar: 'https://i.pravatar.cc/150?img=13',
      verified: true,
    },
    duration: '7:20',
    category: 'Leadership',
    engagement: {
      likes: 567,
      bookmarks: 178,
    },
  },
];

// Mock Articles
export const MOCK_ARTICLES: ArticleContent[] = [
  {
    id: 'art1',
    title: 'Comment rédiger un CV qui se démarque en 2025',
    description: 'Les nouvelles tendances et conseils pour un CV moderne et efficace',
    thumbnail: 'https://picsum.photos/300/200?random=21',
    author: {
      id: 'a5',
      name: 'Emma Leclerc',
      avatar: 'https://i.pravatar.cc/150?img=14',
    },
    category: 'Carrière',
    contentType: 'Lecture courte',
    readingTime: '5 min',
    publishedAt: 'Il y a 1 jour',
    tags: ['CV', 'carrière', 'conseils'],
  },
  {
    id: 'art2',
    title: "L'impact de l'IA générative sur le marché du travail",
    description: 'Analyse des transformations et opportunités à venir dans différents secteurs',
    thumbnail: 'https://picsum.photos/300/200?random=22',
    author: {
      id: 'a6',
      name: 'Alexandre Dupont',
      avatar: 'https://i.pravatar.cc/150?img=15',
    },
    category: 'Tech',
    contentType: 'Étude approfondie',
    readingTime: '12 min',
    publishedAt: 'Il y a 3 jours',
    tags: ['IA', 'tech', 'futur'],
  },
  {
    id: 'art3',
    title: "Comment j'ai négocié une augmentation de 20% en utilisant la méthode STAR",
    description: 'Témoignage et conseils pratiques pour préparer sa négociation salariale',
    thumbnail: 'https://picsum.photos/300/200?random=23',
    author: {
      id: 'a7',
      name: 'Sarah Martin',
      avatar: 'https://i.pravatar.cc/150?img=16',
    },
    category: 'Témoignage',
    contentType: 'Témoignage',
    readingTime: '8 min',
    publishedAt: 'Il y a 1 semaine',
    tags: ['salaire', 'négociation', 'témoignage'],
  },
  {
    id: 'art4',
    title: '5 compétences essentielles pour les managers en 2025',
    description: 'Les soft skills qui feront la différence dans un monde du travail en mutation',
    thumbnail: 'https://picsum.photos/300/200?random=24',
    author: {
      id: 'a8',
      name: 'Paul Durand',
      avatar: 'https://i.pravatar.cc/150?img=17',
    },
    category: 'Leadership',
    contentType: 'Lecture courte',
    readingTime: '6 min',
    publishedAt: 'Il y a 4 jours',
    tags: ['management', 'leadership', 'compétences'],
  },
  {
    id: 'art5',
    title: 'Le guide complet du travail hybride : organisation et productivité',
    description: 'Comment tirer le meilleur parti du modèle hybride et rester efficace',
    thumbnail: 'https://picsum.photos/300/200?random=25',
    author: {
      id: 'a9',
      name: 'Claire Moreau',
      avatar: 'https://i.pravatar.cc/150?img=18',
    },
    category: 'Productivité',
    contentType: 'Étude approfondie',
    readingTime: '15 min',
    publishedAt: 'Il y a 2 semaines',
    tags: ['télétravail', 'hybride', 'productivité'],
  },
  {
    id: 'art6',
    title: "Comment j'ai pivoté ma carrière vers l'UX Design à 40 ans",
    description: 'Parcours, formation et conseils pour une reconversion réussie',
    thumbnail: 'https://picsum.photos/300/200?random=26',
    author: {
      id: 'a10',
      name: 'Philippe Martin',
      avatar: 'https://i.pravatar.cc/150?img=19',
    },
    category: 'Témoignage',
    contentType: 'Témoignage',
    readingTime: '10 min',
    publishedAt: 'Il y a 1 semaine',
    tags: ['reconversion', 'UX', 'témoignage'],
  },
  {
    id: 'art7',
    title: 'Les tendances du recrutement tech en 2025',
    description: 'Ce que recherchent les recruteurs et comment s\'y préparer',
    thumbnail: 'https://picsum.photos/300/200?random=27',
    author: {
      id: 'a11',
      name: 'Sophie Chen',
      avatar: 'https://i.pravatar.cc/150?img=21',
    },
    category: 'Tech',
    contentType: 'Lecture courte',
    readingTime: '7 min',
    publishedAt: 'Il y a 5 jours',
    tags: ['recrutement', 'tech', 'carrière'],
  },
  {
    id: 'art8',
    title: 'Bien-être au travail : les pratiques qui font la différence',
    description: 'Comment les entreprises innovantes améliorent l\'expérience de leurs employés',
    thumbnail: 'https://picsum.photos/300/200?random=28',
    author: {
      id: 'a12',
      name: 'Marie Dupont',
      avatar: 'https://i.pravatar.cc/150?img=22',
    },
    category: 'Bien-être',
    contentType: 'Étude approfondie',
    readingTime: '14 min',
    publishedAt: 'Il y a 3 jours',
    tags: ['bien-être', 'travail', 'management'],
  },
];

// Mock Games
export const MOCK_GAMES: Game[] = [
  {
    id: '1',
    title: 'Intérêts & Motivation',
    duration: '3 min',
    questions: 6,
    description: 'Découvre ce qui t\'anime vraiment et les domaines qui te passionnent',
    credits: 50,
    difficulty: 'Facile',
    icon: 'pulse',
    image: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=800',
    status: 'not-started',
  },
  {
    id: '2',
    title: 'Soft Skills en Action',
    duration: '5 min',
    questions: 8,
    description: 'Évalue tes compétences relationnelles à travers des scénarios concrets',
    credits: 75,
    difficulty: 'Moyen',
    icon: 'trending-up',
    image: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800',
    progress: 25,
    status: 'in-progress',
  },
  {
    id: '3',
    title: 'Cartographie de Compétences',
    duration: '4 min',
    questions: 10,
    description: 'Identifie tes forces techniques et tes axes de progression',
    credits: 60,
    difficulty: 'Facile',
    icon: 'grid',
    image: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=800',
    progress: 70,
    status: 'in-progress',
  },
  {
    id: '4',
    title: 'Intelligence Émotionnelle',
    duration: '6 min',
    questions: 12,
    description: 'Mesure ta capacité à comprendre et gérer tes émotions',
    credits: 80,
    difficulty: 'Moyen',
    icon: 'heart',
    image: 'https://images.unsplash.com/photo-1516389573391-5620a0263801?w=800',
    status: 'not-started',
  },
  {
    id: '5',
    title: 'Leadership & Influence',
    duration: '7 min',
    questions: 15,
    description: 'Découvre ton style de leadership et ton potentiel d\'influence',
    credits: 100,
    difficulty: 'Difficile',
    icon: 'star',
    image: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800',
    status: 'not-started',
  },
  {
    id: '6',
    title: 'Créativité & Innovation',
    duration: '5 min',
    questions: 9,
    description: 'Évalue ta pensée créative et ta capacité d\'innovation',
    credits: 70,
    difficulty: 'Moyen',
    icon: 'bulb',
    image: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800',
    status: 'not-started',
  },
];

// Mock Rooms
export const MOCK_ROOMS: Room[] = [
  {
    id: '1',
    title: 'Campus France',
    type: 'École',
    access: 'Publique',
    description: 'Accompagne la mobilité étudiante internationale et facilite les échanges...',
    tags: ['Mobilité', 'International', 'Études'],
    members: 1250,
    lastActivity: 'Il y a 2h',
    image: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800',
    isActive: true,
  },
  {
    id: '2',
    title: 'Microsoft for Students',
    type: 'Entreprise',
    access: 'Publique',
    description: 'Formations et opportunités tech pour les étudiants et jeunes professionnels.',
    tags: ['Tech', 'Formation', 'Carrière'],
    members: 3450,
    lastActivity: 'Il y a 1j',
    image: 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=800',
    isActive: true,
  },
  {
    id: '3',
    title: 'Women in Tech',
    type: 'Association',
    access: 'Publique',
    description: 'Encourager la diversité dans le numérique et soutenir les femmes...',
    tags: ['Diversité', 'Tech', 'Networking'],
    members: 890,
    lastActivity: 'Il y a 5h',
    image: 'https://images.unsplash.com/photo-1573164713714-d95e436ab8d6?w=800',
    isActive: true,
  },
  {
    id: '4',
    title: 'Entrepreneurs de demain',
    type: 'Communauté',
    access: 'Sur invitation',
    description: 'Communauté d\'entraide pour les jeunes entrepreneurs et porteurs de...',
    tags: ['Entrepreneuriat', 'Innovation', 'Business'],
    members: 720,
    lastActivity: 'Il y a 3h',
    image: 'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=800',
    isActive: true,
  },
  {
    id: '5',
    title: 'HEC Paris Alumni',
    type: 'École',
    access: 'Privée',
    description: 'Réseau des anciens élèves de HEC Paris. Échanges professionnels et opportunités.',
    tags: ['Business', 'Alumni', 'Networking'],
    members: 5600,
    lastActivity: 'Il y a 1j',
    image: 'https://images.unsplash.com/photo-1562774053-701939374585?w=800',
  },
  {
    id: '6',
    title: 'Google Developer Group',
    type: 'Communauté',
    access: 'Publique',
    description: 'Communauté de développeurs passionnés par les technologies Google.',
    tags: ['Développement', 'Google', 'Tech'],
    members: 2300,
    lastActivity: 'Il y a 4h',
    image: 'https://images.unsplash.com/photo-1573167243872-43c6433b9d40?w=800',
  },
  {
    id: '7',
    title: 'Les Restos du Cœur',
    type: 'Association',
    access: 'Sur invitation',
    description: 'Espace de coordination des bénévoles et actions solidaires.',
    tags: ['Solidarité', 'Bénévolat', 'Action sociale'],
    members: 1800,
    lastActivity: 'Il y a 8h',
    image: 'https://images.unsplash.com/photo-1559027615-cd4628902d4a?w=800',
  },
  {
    id: '8',
    title: 'BNP Paribas Talents',
    type: 'Entreprise',
    access: 'Privée',
    description: 'Programme de recrutement et d\'accompagnement des jeunes talents.',
    tags: ['Finance', 'Carrière', 'Banking'],
    members: 950,
    lastActivity: 'Il y a 2j',
    image: 'https://images.unsplash.com/photo-1601597111158-2fceff292cdc?w=800',
  },
  {
    id: '9',
    title: 'Sciences Po Alumni',
    type: 'École',
    access: 'Privée',
    description: 'Réseau des diplômés de Sciences Po. Événements et opportunités professionnelles.',
    tags: ['Politique', 'Sciences sociales', 'Alumni'],
    members: 4200,
    lastActivity: 'Il y a 1j',
    image: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800',
  },
  {
    id: '10',
    title: 'Designers français',
    type: 'Communauté',
    access: 'Publique',
    description: 'Communauté de designers francophones pour partager projets et conseils.',
    tags: ['Design', 'UX/UI', 'Créativité'],
    members: 1450,
    lastActivity: 'Il y a 8h',
    image: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800',
  },
  {
    id: '11',
    title: 'L\'Oréal Careers',
    type: 'Entreprise',
    access: 'Publique',
    description: 'Opportunités de carrière et programme de mentorat chez L\'Oréal.',
    tags: ['Beauté', 'Marketing', 'Carrière'],
    members: 780,
    lastActivity: 'Il y a 3j',
    image: 'https://images.unsplash.com/photo-1522543558187-768b6df7c25c?w=800',
  },
  {
    id: '12',
    title: 'Greenpeace France',
    type: 'Association',
    access: 'Publique',
    description: 'Coordination des actions et sensibilisation pour la protection de l\'environnement.',
    tags: ['Écologie', 'Activisme', 'Environnement'],
    members: 2100,
    lastActivity: 'Il y a 5h',
    image: 'https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=800',
  },
];

// Mock Formations
export const MOCK_FORMATIONS: Formation[] = [
  {
    id: 'f1',
    title: 'Leadership et management d\'équipe',
    description: 'Développe tes compétences en leadership et apprends à gérer efficacement une équipe dans un...',
    thumbnail: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=800',
    provider: {
      id: 'p1',
      name: 'Harvard Business School',
      logo: 'https://i.pravatar.cc/150?img=30',
    },
    category: 'Leadership',
    level: 'Intermédiaire',
    duration: '8 semaines',
    rating: 4.8,
    reviewCount: 1245,
    matchPercentage: 95,
    isFree: true,
    isFeatured: true,
  },
  {
    id: 'f2',
    title: 'Data Science pour les managers',
    description: 'Une introduction pratique à la data science pour les professionnels qui souhaitent comprendre et utiliser...',
    thumbnail: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800',
    provider: {
      id: 'p2',
      name: 'MIT',
      logo: 'https://i.pravatar.cc/150?img=31',
    },
    category: 'Data',
    level: 'Débutant',
    duration: '6 semaines',
    rating: 4.6,
    reviewCount: 892,
    matchPercentage: 88,
    isFree: true,
    isFeatured: true,
  },
  {
    id: 'f3',
    title: 'Communication efficace en milieu professionnel',
    description: 'Améliore tes compétences en communication pour mieux collaborer, présenter tes idées et influencer...',
    thumbnail: 'https://images.unsplash.com/photo-1553028826-f4804a6dba3b?w=800',
    provider: {
      id: 'p3',
      name: 'Stanford',
      logo: 'https://i.pravatar.cc/150?img=32',
    },
    category: 'Communication',
    level: 'Intermédiaire',
    duration: '4 semaines',
    rating: 4.9,
    reviewCount: 1567,
    matchPercentage: 92,
    isFree: true,
    isFeatured: true,
  },
  {
    id: 'f4',
    title: 'Gestion de projet Agile et Scrum',
    description: 'Maîtrise les méthodologies agiles et deviens un Scrum Master certifié pour gérer des projets complexes...',
    thumbnail: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800',
    provider: {
      id: 'p4',
      name: 'Google',
      logo: 'https://i.pravatar.cc/150?img=33',
    },
    category: 'Gestion de projet',
    level: 'Intermédiaire',
    duration: '5 semaines',
    rating: 4.7,
    reviewCount: 2134,
    matchPercentage: 90,
    isFree: true,
  },
  {
    id: 'f5',
    title: 'Marketing Digital et Growth Hacking',
    description: 'Apprends les stratégies de marketing digital les plus performantes et comment développer rapidement...',
    thumbnail: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800',
    provider: {
      id: 'p5',
      name: 'HEC Paris',
      logo: 'https://i.pravatar.cc/150?img=34',
    },
    category: 'Marketing',
    level: 'Débutant',
    duration: '6 semaines',
    rating: 4.5,
    reviewCount: 987,
    matchPercentage: 85,
    isFree: true,
  },
  {
    id: 'f6',
    title: 'Intelligence Artificielle et Machine Learning',
    description: 'Découvre les fondamentaux de l\'IA et du machine learning avec des cas pratiques et des projets...',
    thumbnail: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800',
    provider: {
      id: 'p6',
      name: 'Coursera',
      logo: 'https://i.pravatar.cc/150?img=35',
    },
    category: 'Tech',
    level: 'Avancé',
    duration: '10 semaines',
    rating: 4.9,
    reviewCount: 3421,
    matchPercentage: 93,
    isFree: false,
  },
];

// Mock Job Offers
export const MOCK_JOB_OFFERS: JobOffer[] = [
  {
    id: 'job1',
    title: 'UX/UI Designer',
    company: 'DigitalCraft',
    companyLogo: 'https://i.pravatar.cc/150?img=40',
    category: 'Design',
    location: 'Paris',
    workType: 'Hybride',
    contractType: 'CDI',
    experienceLevel: 'Intermédiaire',
    salary: '45,000 - 55,000 €/an',
    skills: ['Figma', 'Adobe XD', 'Prototypage', 'UI Design', 'User Research'],
    postedDate: 'Il y a 2 jours',
    matchPercentage: 92,
    isRecommended: true,
    isFavorite: false,
  },
  {
    id: 'job2',
    title: 'Développeur Frontend React',
    company: 'TechSolutions',
    companyLogo: 'https://i.pravatar.cc/150?img=41',
    category: 'Tech',
    location: 'Lyon',
    workType: 'Télétravail',
    contractType: 'CDI',
    experienceLevel: 'Intermédiaire',
    salary: '40,000 - 60,000 €/an',
    skills: ['React', 'TypeScript', 'CSS', 'JavaScript', 'Redux'],
    postedDate: 'Il y a 5 jours',
    matchPercentage: 88,
    isRecommended: true,
    isFavorite: true,
  },
  {
    id: 'job3',
    title: 'Chef de Projet Marketing Digital',
    company: 'MarketBoost',
    companyLogo: 'https://i.pravatar.cc/150?img=42',
    category: 'Marketing',
    location: 'Bordeaux',
    workType: 'Hybride',
    contractType: 'CDI',
    experienceLevel: 'Expérimenté',
    salary: '50,000 - 65,000 €/an',
    skills: ['SEO', 'SEM', 'Réseaux sociaux', 'Google Analytics', 'Content Marketing'],
    postedDate: 'Il y a 1 jour',
    matchPercentage: 85,
    isRecommended: true,
    isFavorite: true,
  },
  {
    id: 'job4',
    title: 'Data Scientist',
    company: 'DataInsight',
    companyLogo: 'https://i.pravatar.cc/150?img=43',
    category: 'Tech',
    location: 'Paris',
    workType: 'Sur site',
    contractType: 'CDI',
    experienceLevel: 'Expert',
    salary: '55,000 - 75,000 €/an',
    skills: ['Python', 'Machine Learning', 'SQL', 'TensorFlow', 'Data Viz'],
    postedDate: 'Il y a 3 jours',
    matchPercentage: 78,
    isRecommended: false,
    isFavorite: false,
  },
  {
    id: 'job5',
    title: 'Responsable Ressources Humaines',
    company: 'TalentFirst',
    companyLogo: 'https://i.pravatar.cc/150?img=44',
    category: 'RH',
    location: 'Nantes',
    workType: 'Sur site',
    contractType: 'CDI',
    experienceLevel: 'Expérimenté',
    salary: '45,000 - 60,000 €/an',
    skills: ['Recrutement', 'GPEC', 'Droit du travail', 'Formation', 'Paie'],
    postedDate: 'Il y a 1 semaine',
    matchPercentage: 72,
    isRecommended: false,
    isFavorite: false,
  },
  {
    id: 'job6',
    title: 'Développeur Backend Node.js',
    company: 'ServerPro',
    companyLogo: 'https://i.pravatar.cc/150?img=45',
    category: 'Tech',
    location: 'Marseille',
    workType: 'Télétravail',
    contractType: 'Freelance',
    experienceLevel: 'Intermédiaire',
    salary: '400 - 600 €/jour',
    skills: ['Node.js', 'Express', 'MongoDB', 'REST API', 'Docker'],
    postedDate: 'Il y a 4 jours',
    matchPercentage: 80,
    isRecommended: false,
    isFavorite: true,
  },
];

